services:
  postgres: 
    container_name: postgres_desafio
    image: postgres:latest
    environment:
      - POSTGRES_DB=desafio
      - POSTGRES_PASSWORD=pgadmin
    ports:
      - 5432:5432
    volumes:
      - data:/data/db
  
  api:
    container_name: api_go
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - postgres
  
  front:
    container_name: front_end
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - api


volumes:
  data: