services:
  postgres: 
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=desafio
      - POSTGRES_PASSWORD=pgadmin
    ports:
      - 5432:5432
    volumes:
      - data:data/db


volumes:
  data: